import type { Metadata } from "next";
import { Slackey } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import Providers from "./Providers";
import Header from "./components/Header";

const inter = Slackey({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <Navbar />
            <Header />
            <div className="h-[1000px]">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
